### ISSUE TITLE
Webthings Not Starting Mysensors Adapter Ubuntu 18.04

### ISSUE THREAD

**Issue by Westiewombat** [createcandle/Webthings-mysensors-adapter#14]
Hi, I have Webthings running on Ubuntu 18.04. I have it up and running and have added the Weather add-ons and Time adapter.

I'm getting an error thrown 
2020-08-14 17:48:34.055 INFO   : Plugin: mysensors-adapter died, code = 1 restarting after 30000
2020-08-14 17:49:04.220 ERROR  : mysensors-adapter: Traceback (most recent call last):
2020-08-14 17:49:04.220 ERROR  : mysensors-adapter:   File "/home/clive/.mozilla-iot/addons/mysensors-adapter/main.py", line 11, in <module>
2020-08-14 17:49:04.220 ERROR  : mysensors-adapter:     from pkg.mysensors_adapter import MySensorsAdapter  # noqa
2020-08-14 17:49:04.221 ERROR  : mysensors-adapter:   File "/home/clive/.mozilla-iot/addons/mysensors-adapter/pkg/mysensors_adapter.py", line 23, in <module>
2020-08-14 17:49:04.221 ERROR  : mysensors-adapter:     from gateway_addon import Adapter, Database
2020-08-14 17:49:04.221 ERROR  : mysensors-adapter: ModuleNotFoundError: No module named 'gateway_addon'

I have checked and the adapter is there and is fresh in the .mozilla-iot/addons.

The Webthings was installed by hand because of a dependency issues with the .deb around nodejs version, so followed the instructions for the source/complile using npm. The gateway code is running in my Downloads folder.

Any help appreciated

**Comment by Westiewombat** [comment]
Hi - it was a python version issue - seems there are a lot of different versions on my machine - had to force the install of modules into the correct version for the various module errors
sudo python3.6 -m pip install websocket-client
