### ISSUE TITLE
Loop close error

### ISSUE THREAD

**Issue by createcandle** [createcandle/Webthings-mysensors-adapter#2]
2019-05-07 19:10:12.103 INFO   : mysensors: AddonMangerProxy: recv: b'{"messageType":"unloadPlugin","data":{"pluginId":"mysensors-adapter"}}'
2019-05-07 19:10:15.101 INFO   : Killing mysensors-adapter plugin.
2019-05-07 19:10:15.108 ERROR  : mysensors: Exception in thread Thread-24:
2019-05-07 19:10:15.117 ERROR  : mysensors: Traceback (most recent call last):
2019-05-07 19:10:15.120 ERROR  : mysensors:   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
2019-05-07 19:10:15.122 ERROR  : mysensors:     self.run()
2019-05-07 19:10:15.125 ERROR  : mysensors:   File "/usr/lib/python3.5/threading.py", line 862, in run
2019-05-07 19:10:15.128 ERROR  : mysensors:     self._target(*self._args, **self._kwargs)
2019-05-07 19:10:15.131 ERROR  : mysensors:   File "/usr/local/lib/python3.5/dist-packages/gateway_addon/addon_manager_proxy.py", line 278, in unload_fn
2019-05-07 19:10:15.134 ERROR  : mysensors:     adapter.unload()
2019-05-07 19:10:15.137 ERROR  : mysensors:   File "/home/pi/.mozilla-iot/addons/mysensors-adapter/pkg/mysensors_adapter.py", line 100, in unload
2019-05-07 19:10:15.139 ERROR  : mysensors:     self.LOOP.close()
2019-05-07 19:10:15.142 ERROR  : mysensors:   File "/usr/lib/python3.5/asyncio/unix_events.py", line 63, in close
2019-05-07 19:10:15.145 ERROR  : mysensors:     super().close()
2019-05-07 19:10:15.149 ERROR  : mysensors:   File "/usr/lib/python3.5/asyncio/selector_events.py", line 107, in close
2019-05-07 19:10:15.151 ERROR  : mysensors:     raise RuntimeError("Cannot close a running event loop")
2019-05-07 19:10:15.154 ERROR  : mysensors: RuntimeError: Cannot close a running event loop
2019-05-07 19:10:15.157 ERROR  : mysensors:

**Comment by createcandle** [comment]
May be fixed in version 0.1.2
